version: '3.6'

services:
  redis:
    image: redis:alpine
    hostname: redis
    container_name: redis
    restart: always
    command: redis-server --requirepass secrets
    ports:
      - '6379:6379'
